"""
FitPlan DSL — Markdown Generator (v2)
"""

import os
from datetime import datetime
from os.path import join

import click
from textx import generator

from ..main import parse_model
from ..nutrition_calc import calc_nutrition_for_day, calc_nutrition_for_recipe
from ..plan_generator import generate_weekly_plan, get_workouts_for_day, DAYS

WORKOUT_EMOJI = {
    'running': '🏃', 'cycling': '🚴', 'swimming': '🏊', 'weightlifting': '🏋️',
    'yoga': '🧘', 'pilates': '🤸', 'hiit': '⚡', 'walking': '🚶',
    'rowing': '🚣', 'elliptical': '🔄', 'hiking': '🥾', 'other': '💪',
}

GOAL_DESC = {
    'weightLoss': 'Weight Loss', 'muscleGain': 'Muscle Gain',
    'maintenance': 'Maintenance', 'endurance': 'Endurance',
}


@generator('fitplan', 'md')
def md_generator(metamodel, model, output_path, overwrite, debug, **kwargs):
    """Generates Markdown plan from .fitplan file."""
    input_file = model._tx_filename
    base_dir = output_path if output_path else os.path.dirname(input_file)
    base_name, _ = os.path.splitext(os.path.basename(input_file))
    output_file = os.path.abspath(join(base_dir, f"{base_name}_plan.md"))

    if not overwrite and os.path.exists(output_file):
        click.echo(f'-- Skipping: {output_file}')
        return

    click.echo(f'-> Generating Markdown plan: {output_file}')

    fitplan_model, warnings = parse_model(input_file)
    if fitplan_model is None:
        return

    declarations = fitplan_model.declarations
    custom_ingredients = [d for d in declarations if d.__class__.__name__ == 'Ingredient']
    recipes = [d for d in declarations if d.__class__.__name__ == 'Recipe']
    workouts = [d for d in declarations if d.__class__.__name__ == 'Workout']
    plans = [d for d in declarations if d.__class__.__name__ == 'Plan']

    lines = []
    now = datetime.now().strftime('%d.%m.%Y %H:%M')
    lines.append(f'# 🥗 FitPlan — Weekly Plan\n')
    lines.append(f'> Generated by FitPlan DSL · {now}\n')
    lines.append('---\n')

    # Recipes
    if recipes:
        lines.append('## 📋 Recipes\n')
        for recipe in recipes:
            nutrition = calc_nutrition_for_recipe(recipe, custom_ingredients, servings=1)
            lines.append(f'### {recipe.name}\n')
            lines.append(f'- **Time:** {recipe.time} min · **Serves:** {recipe.serves} · **Difficulty:** {recipe.difficulty}')
            lines.append(f'- **Per serving:** {nutrition["calories"]:.0f} kcal · {nutrition["protein"]:.1f}g protein · {nutrition["carbs"]:.1f}g carbs · {nutrition["fat"]:.1f}g fat')
            if recipe.tags:
                lines.append(f'- **Tags:** {", ".join("#" + t for t in recipe.tags)}')
            lines.append('')
            lines.append('**Ingredients:**\n')
            for item in recipe.items:
                lines.append(f'- {item.ingredient}: {item.amount} {item.unit}')
            lines.append('')
            lines.append('**Steps:**\n')
            for i, step in enumerate(recipe.steps, 1):
                meta = []
                if step.duration:
                    meta.append(f'{step.duration} min')
                if step.temperature:
                    meta.append(f'{step.temperature}°C')
                meta_str = f' _({", ".join(meta)})_' if meta else ''
                lines.append(f'{i}. {step.description}{meta_str}')
            lines.append('\n---\n')

    # Workouts
    if workouts:
        lines.append('## 🏋️ Workout Schedule\n')
        for w in workouts:
            emoji = WORKOUT_EMOJI.get(w.type, '💪')
            burns_str = f' · Burns ~{w.burns} kcal' if w.burns else ''
            lines.append(f'- {emoji} **{w.name}** — {w.type}, {w.duration} min, {w.intensity} intensity{burns_str}')
            lines.append(f'  - Days: {", ".join(w.days)}')
        lines.append('\n---\n')

    # Plans
    for plan in plans:
        weekly = generate_weekly_plan(plan, recipes)
        goal_desc = GOAL_DESC.get(plan.goal, plan.goal)

        lines.append(f'## 📅 {plan.name}\n')
        lines.append(f'| | |')
        lines.append(f'|---|---|')
        lines.append(f'| **Goal** | {goal_desc} |')
        lines.append(f'| **Target calories** | {plan.target_calories} kcal/day |')
        lines.append(f'| **Macros** | Protein {plan.protein_pct}% · Carbs {plan.carbs_pct}% · Fat {plan.fat_pct}% |')
        lines.append('')

        lines.append('### 📆 Auto-Generated Schedule\n')

        week_kcal = 0
        for day in DAYS:
            day_plan = weekly.get(day, {})
            day_nutrition = calc_nutrition_for_day(day_plan, custom_ingredients)
            day_kcal = day_nutrition['calories']
            week_kcal += day_kcal
            day_workouts = get_workouts_for_day(workouts, day)

            lines.append(f'#### {day}\n')
            workout_burns = sum(w.burns if w.burns else 0 for w in day_workouts)
            net_kcal = day_kcal - workout_burns
            meal_table = ['| Meal | Recipe | Calories |', '|---|---|---|']
            for meal_type in ['breakfast', 'lunch', 'dinner', 'snack']:
                if meal_type in day_plan:
                    recipe = day_plan[meal_type]['recipe']
                    servings = day_plan[meal_type].get('servings', 1)
                    kcal = calc_nutrition_for_recipe(recipe, custom_ingredients, servings)['calories']
                    emoji = {'breakfast': '🌅', 'lunch': '☀️', 'dinner': '🌙', 'snack': '🍎'}[meal_type]
                    meal_table.append(f'| {emoji} {meal_type.capitalize()} | {recipe.name} | {kcal:.0f} kcal |')
            meal_table.append(f'| **Total** | | **{day_kcal:.0f} eaten / {net_kcal:.0f} net** |')
            lines.extend(meal_table)
            lines.append('')

            if day_workouts:
                for w in day_workouts:
                    emoji = WORKOUT_EMOJI.get(w.type, '💪')
                    burns = f' · -{w.burns} kcal' if w.burns else ''
                    lines.append(f'**Workout:** {emoji} {w.name} · {w.duration} min · {w.intensity}{burns}')
                lines.append('')

            diff = net_kcal - plan.target_calories
            diff_str = f'+{diff:.0f}' if diff > 0 else f'{diff:.0f}'
            status = '✅' if abs(diff) <= plan.target_calories * 0.1 else ('⬆️' if diff > 0 else '⬇️')
            lines.append(f'> {status} Difference from target: {diff_str} kcal\n')
            lines.append('---\n')

        avg_kcal = week_kcal / 7
        lines.append('### 📊 Weekly Summary\n')
        lines.append(f'| Stat | Value |')
        lines.append(f'|---|---|')
        lines.append(f'| Total calories | {week_kcal:.0f} kcal |')
        lines.append(f'| Daily average | {avg_kcal:.0f} kcal |')
        lines.append(f'| Target per day | {plan.target_calories} kcal |')
        lines.append('')

    lines.append(f'\n---\n*FitPlan DSL · {now}*')

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    click.echo(f'OK Markdown plan: {output_file}')